### ISSUE TITLE
take reports file sizes in YB in python3

### ISSUE THREAD

**Issue by dshrader** [hpc/give#6]
When using python 3, take reports file sizes in YB:

```bash
$> python --version
Python 2.7.5
$> take
 jgreen has given:
   189  B May 28 09:36 yum.out
     9 MB Jul 17 14:55 zerolibs.txt
   2 file(s)
You have 2 file(s) to take.
$> module load python/3.6 
$> python --version
Python 3.6.3 :: Anaconda, Inc.
$> take
 jgreen has given:
     0 YB May 28 09:36 yum.out
     0 YB Jul 17 14:55 zerolibs.txt
   2 file(s)
You have 2 file(s) to take.
```

This is with give version 3.1-4 (as reported via rpm).

I believe the issue is in the list_a_file method in take. It uses a set of conditionals to decide what units to display file sizes in. Between python 2 and 3, the `/` operator changed from integer to floating point division, so all of the conditionals now return a value greater than 0. This means the first condition evaluates to true all of the time, which leads to YB being the unit.

Here is the division that list_a_file relies on done in both python 2 and 3 to illustrate what is going on:

```bash
$> python --version
Python 2.7.5
$> python -c "print(20 / 2**80)"
0
$> module load python/3.6
$> python --version
Python 3.6.3 :: Anaconda, Inc.
$> python -c "print(20 / 2**80)"
1.6543612251060553e-23
```

I can see two possible ways of fixing this:
1. Change all of the `/` operators in the conditionals to `//` operators (recovers integer division in python 3, and works in python 2.7).
2. Change all of the the `> 0` to `> 1` in the conditionals.

There might be other solutions, too.

Thanks,
David

**Comment by dshrader** [comment]
Here is a patch that changes the limits of the comparison to use `>= 1`. I felt better about this solution than using `//` as it seemed more stable/less prone to change. This solution shouldn't change any of the reported values by take.

[take_patch.txt](https://github.com/hpc/give/files/3637035/take_patch.txt)

**Comment by dmanno** [comment]
Thanks for the feedback and patch. The spirit of the original code and intuition when looking at this block is integer division. Going to modify to keep integer division. I believe there is a 3.1-5 version in the latest TOSS release that implements this as such, so we'll be in line with versions.
